### ISSUE TITLE
新增pool的时候没有保存EnvTreeId，查看pool详细信息需要返回EnvTree对象：{ Id, Name }

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#12]
新增pool的时候没有保存EnvTreeId，查看pool详细信息需要返回EnvTree对象：{ Id, Name }

**Comment by uniseraph** [comment]
在pool创建时候根据env_tree_id从env_tree_meta表中获取env_tree_name并保存到pool表中；
