### ISSUE TITLE
保存模板出错：json: cannot unmarshal string into Go value of type int

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#14]
{"Title":"s","Name":"s","Version":"s","Description":"","Services":[{"Id":0,"Title":"a","Name":"a","ImageName":"a","ImageTag":"1.0.1","CPU":"2","ExclusiveCPU":true,"Memory":"500","ReplicaCount":1,"Description":"","Command":"","Restart":"always","Envs":[{"index":0,"Id":0,"Name":"a.b","Value":"${ENV_1}"}],"Ports":[{"index":0,"Id":0,"SourcePort":"8080","LoadBalancerId":""}],"Volumns":[],"Labels":[],"hidden":false}]}

**Comment by uniseraph** [comment]
在template相关结构定义中，设置int／int64字段的json tag为string

type Service struct {
	Title        string
	Name         string
	ImageName    string
	ImageTag     string
	CPU          int       `json:",string"`
	ExclusiveCPU bool
	Memory       int       `json:",string"`
	ReplicaCount int       `json:",string"`
	Description  string
	Restart      string
	Command      string
	Envs         []Env
	Volumns      []Volumne
	Labels       []Label
}
