### ISSUE TITLE
Pool的update接口没有实现

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#27]
POST内容：
{
     "Name": "...."
     // 后续可能会添加其他可修改属性
}

**Comment by cbcbbcbc** [comment]
@uniseraph

**Comment by uniseraph** [comment]
type PoolUpdateRequest  struct {
	Id string
	Name string
	Labels []string `json:",omitempty"`
	EnvTreeId string
	EnvTreeName string
}

对于pool，id用于唯一确定一个pool，其他字段可以编辑修改

**Comment by uniseraph** [comment]
@cbcbbcbc @charlescui

**Comment by cbcbbcbc** [comment]
@charlescui 目前暂时只修改Name

**Comment by cbcbbcbc** [comment]
只能Update Name
@charlescui
