### ISSUE TITLE
升级应用出错

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#31]
DEBU[1467] HTTP request received                         localHandler=&{0x1544360 0x1549520 6} method=POST uri="/api/applications/596861fd421aa970d48185ba/upgrade"
DEBU[1467] HGETALL content: &redis.StringStringMapCmd{baseCmd:redis.baseCmd{_args:[]interface {}{"hgetall", "redis.uid.session.cefa2960-685a-11e7-86d6-542696d68b2d"}, err:error(nil), _readTimeout:(*time.Duration)(nil)}, val:map[string]string{"uid":"59685fb04e8ea2c5dd8f2c33", "roleSet":"4"}} 
INFO[1467] SessionContent: map[string]string{"uid":"59685fb04e8ea2c5dd8f2c33", "roleSet":"4"} 
ERRO[1467] HTTP error: EOF                               status=400

**Comment by cbcbbcbc** [comment]
@uniseraph

**Comment by uniseraph** [comment]
reqest body不能为空

**Comment by uniseraph** [comment]
application表拼写错位
