### ISSUE TITLE
回滚应用没有实现

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#33]
@uniseraph

**Comment by uniseraph** [comment]
完成

**Comment by cbcbbcbc** [comment]
回滚失败：
DEBU[0567] HTTP request received                         localHandler=&{0x1548a40 0x1550280 6} method=POST uri="/api/applications/59686a6b421aa97b9434de55/rollback"
DEBU[0567] HGETALL content: &redis.StringStringMapCmd{baseCmd:redis.baseCmd{_args:[]interface {}{"hgetall", "redis.uid.session.564aebdf-6942-11e7-8792-542696d68b2d"}, err:error(nil), _readTimeout:(*time.Duration)(nil)}, val:map[string]string{"roleSet":"4", "uid":"59686a220c7a15d9439f5afb"}} 
INFO[0567] SessionContent: map[string]string{"roleSet":"4", "uid":"59686a220c7a15d9439f5afb"} 
ERRO[0567] HTTP error: no such a deployment:59686a6b421aa97b9434de55  status=404

@uniseraph
