### ISSUE TITLE
/audit/ssh返回结果错误

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#42]
{"Token":"ssh -p %!s(int=2022) 5e8a5ee4_6930_11e7_8495_542696d68b2d@47.92.49.245"}
（1）端口号错误；
（2）不要叫Token，叫Command，返回的是一个完整的命令，token只是其中的一截；

@charlescui

**Comment by charlescui** [comment]
Fix bff8e46fe58cbdea7ca62e8255c7f262915ae5c9

**Comment by cbcbbcbc** [comment]
验证通过
