### ISSUE TITLE
/audit/list接口错误

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#44]
DEBU[0472] HTTP request received                         localHandler=&{0x154a8a0 0x154fe80 5} method=POST uri="/api/audit/list"
DEBU[0472] HGETALL content: &redis.StringStringMapCmd{baseCmd:redis.baseCmd{_args:[]interface {}{"hgetall", "redis.uid.session.ae4fa077-6927-11e7-a97c-542696d68b2d"}, err:error(nil), _readTimeout:(*time.Duration)(nil)}, val:map[string]string{"uid":"59686a220c7a15d9439f5afb", "roleSet":"4"}} 
INFO[0472] SessionContent: map[string]string{"uid":"59686a220c7a15d9439f5afb", "roleSet":"4"} 
ERRO[0472] HTTP error: json: cannot unmarshal number into Go struct field GetAuditListRequest.StartTime of type string  status=400

@charlescui

**Comment by charlescui** [comment]
FIX bff8e46fe58cbdea7ca62e8255c7f262915ae5c9

**Comment by cbcbbcbc** [comment]
@charlescui 没有改正确，依然老错误
