### ISSUE TITLE
/dashboard接口需求

### ISSUE THREAD

**Issue by cbcbbcbc** [uniseraph/apiserver#99]
请求参数：
		PoolId: 
		StartTime: 趋势统计的起始日期，例如：'2017-5-1'
	返回：{
		Summary: {
			Nodes: 总节点数，
			CPUs: 总CPU数,
			CPUsUsed:
			Memory: 总内存字节数,
			MemoryUsed:
			Disk: 总磁盘空间字节,
			DiskUsed:

			DataDisk: {
				Disks: 6,
				DisksUsed: 4,
				DiskSpace:字节,
				DiskSpaceUsed:字节
			},

			Applications:
			Containers:

			OutstandingServices: [
				{ Id, Title, Name, Application: { Id, Title, Name, Version }, CPU, ExclusiveCPU, Memory, ReplicaCount }
			]
		},
		Trend: {
			Upgrades: [
				{ '2017-05-01': 2 },
				{ '2017-05-02': 0 },
				... // 每天一条记录，即使没有数据也要有记录
				{ '2017-07-28': 1 }
			], 
			Rollbacks: [
				{ '2017-05-01': 2 },
				{ '2017-05-02': 0 },
				... // 每天一条记录，即使没有数据也要有记录
				{ '2017-07-28': 1 }
			], 
			MostUpgradeApplications: [
				{ Id, Title, Name, Version, Upgrades }
			],
			MostRollbackApplications: [
				{ Id, Title, Name, Version, Rollbacks }
			]
		}
	}

**Comment by uniseraph** [comment]
目前cpu/memory/disk使用量没取上来，待确认
